# Build settings
# permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: end2end
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://lenamasek.website
baseurl: "lenamasek.github.io"
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/lenamasek/lenamasek.github.io
disqus_shortname: 
disqus_site_shortname:

# Author settings
author:
  name      : Lena Masek
  job       : designer/developer
  bio       : "transhumanist. insubordinate. passionate about psychology and emotional intelligence. designer & developer."
  thumb     : /images/author.jpg
  email     : lena.masek@gmail.com
  url       : http://lenamasek.website
  github    : http://github.com/lenamasek
  twitter   : http://twitter.com/lenamasek
  facebook  : 
  linkedin  : http://linkedin.com/in/lenamasek

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
