# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://lenamasek.website
baseurl: http://lenamasek.website
title: Lena Masek
author: Lena Masek
description: Personal blog and resume
avatar: profile.png
email: lena.masek@email.com
github: lenamasek # username
twitter: lenamasek
linkedin: lenamasek
stackoverflow: users/4338939/lena   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: 
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
