# Site settings
title: lena masek
email: lena.masek@gmail.com
description: "i do both web design & development and print design & production. i work at [torque](http://torque.digital) and freelance on the side. i'd love to work on your project with you. i have experience with websites to promote events, products, individuals, and small businesses."
baseurl: "lenamasek.website" # the subpath of your site, e.g. /blog/
url: "http://lenamasek.website" # the base hostname & protocol for your site
twitter_username: lenamasek
github_username:  lenamasek
instagram_username: lenamasek
google_play: ''
google_plus_com: ''  # Community link
google_plus_per: ''  #Personal link
facebook_app_id: 

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'gdgmanagua'

# Google Analytics 
ga_domain: lenamasek.website
ga_tracking_id: UA-43033620-3


# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

##7b68ee