name: lena masek
markdown: redcarpet
pygments: true
description: "i'm lena masek. i do web + print design/development at a marketing agency and as a freelancer. i also design and build small sites for people, products, and small businesses."
url: "lenamasek.com"
permalink: /posts/:title