# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lenamasek.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: lena masek
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "print + web design & development" # used by search engines

  # Header and footer text
  header_text: >
     <p>i'm lena masek. i work on web + print projects at torque from concepting/ideation to front-end web development to print production. i also freelance the same for people, products, and small businesses.</p>

  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "lena.masek@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "lenamasek"
  google_plus:
  instagram: "lenamasek"
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr: "animatemyveins"
  twitter: "lenamasek"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
